/**
 * Gmail CSS property and HTML element whitelists.
 *
 * Based on observed Gmail rendering behavior and
 * developers.google.com/workspace/gmail/design/css.
 * Gmail strips everything not on these lists.
 */

export const ALLOWED_CSS_PROPERTIES = new Set([
  // Typography
  'color',
  'font',
  'font-family',
  'font-size',
  'font-style',
  'font-variant',
  'font-weight',
  'letter-spacing',
  'line-height',
  'text-align',
  'text-decoration',
  'text-indent',
  'text-overflow',
  'text-transform',
  'white-space',
  'word-spacing',
  'word-break',
  'word-wrap',

  // Box model
  'border',
  'border-top',
  'border-right',
  'border-bottom',
  'border-left',
  'border-color',
  'border-top-color',
  'border-right-color',
  'border-bottom-color',
  'border-left-color',
  'border-style',
  'border-top-style',
  'border-right-style',
  'border-bottom-style',
  'border-left-style',
  'border-width',
  'border-top-width',
  'border-right-width',
  'border-bottom-width',
  'border-left-width',
  'border-radius',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-left-radius',
  'border-bottom-right-radius',
  'border-collapse',
  'border-spacing',
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'width',
  'min-width',
  'max-width',
  'height',
  'min-height',
  'max-height',

  // Background (color only — images/gradients are unreliable in Gmail)
  'background',
  'background-color',

  // Layout
  'display',
  'float',
  'clear',
  'overflow',
  'visibility',
  'vertical-align',

  // Table
  'caption-side',
  'empty-cells',
  'table-layout',

  // List
  'list-style',
  'list-style-type',
  'list-style-position',

  // Other
  'direction',
  'opacity',
  'quotes',
]);

export const ALLOWED_ELEMENTS = new Set([
  'a',
  'abbr',
  'address',
  'b',
  'big',
  'blockquote',
  'br',
  'caption',
  'cite',
  'code',
  'col',
  'colgroup',
  'dd',
  'div',
  'dl',
  'dt',
  'em',
  'font',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'hr',
  'i',
  'img',
  'label',
  'li',
  'ol',
  'p',
  'pre',
  'q',
  's',
  'small',
  'span',
  'strike',
  'strong',
  'sub',
  'sup',
  'table',
  'tbody',
  'td',
  'tfoot',
  'th',
  'thead',
  'tr',
  'tt',
  'u',
  'ul',
]);

export const UNSAFE_ELEMENTS = new Set([
  'script',
  'style',
  'link',
  'meta',
  'iframe',
  'frame',
  'frameset',
  'form',
  'input',
  'button',
  'select',
  'textarea',
  'object',
  'embed',
  'applet',
  'video',
  'audio',
  'source',
  'track',
  'svg',
  'math',
  'canvas',
  'template',
  'slot',
  'noscript',
]);

export const ALLOWED_ATTRIBUTES = new Set([
  'style',
  'href',
  'src',
  'alt',
  'title',
  'width',
  'height',
  'colspan',
  'rowspan',
  'align',
  'valign',
  'dir',
  'target',
  'rel',
  'border',
  'cellpadding',
  'cellspacing',
]);
